apiVersion: v1
kind: Service

metadata:
  name: toxicityclassifier-service

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30008
  selector:
    app: toxicityclassifier
    type: back-end